Models/DayuseModel.cs
using System.ComponentModel.DataAnnotations;

namespace Controle.Models
{
    public class DayuseModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Por favor insira o nome do cliente")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Por favor insira a data de venda")]
        public DateTime DataVenda { get; set; }

        [Required(ErrorMessage = "Por favor insira o telefone do cliente")]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "Por favor insira o numero da pulseira")]
        public string Pulseira { get; set; }
        [Required(ErrorMessage = "Por favor insira se é aluno")]
        public bool Aluno { get; set; }

        [Required(ErrorMessage = "Por favor insira o valor cobrado")]
        public double Preco { get; set; }

        [Required(ErrorMessage = "Por favor insira a forma de pagamento")]
        public string FormaPagamento { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime EditedAt { get; set; }
       


    public string DataVendaFormatada
        {
            get
            {
                return DataVenda.ToString("dd/MM/yyyy");
            }
        }


    }
}

Models/ErrorViewModel.cs
namespace Controle.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CadastroController.cs
using Controle.data;
using Controle.Models;
using Microsoft.AspNetCore.Mvc;

namespace Controle.Controllers
{
    public class CadastroController : Controller
    {

        readonly private ApplicationDbContext _db;

        public CadastroController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public IActionResult Index ()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Index (DayuseModel dayuse)
        {
            if (ModelState.IsValid)
            {
                _db.Dayuse.Add(dayuse);
                _db.SaveChanges();
                TempData["Mensagem de Sucesso"] = "Cadastro Realizado com Sucesso !";

                return RedirectToAction("Index");
            }
            TempData["Mensagem de Erro"] = "Aconteceu algo de errado e não foi possivel cadastrar!";
            return View();

        }
    }
}

Controllers/EditarController.cs
using Controle.data;
using Controle.Models;
using Microsoft.AspNetCore.Mvc;

namespace Controle.Controllers
{
    public class EditarController : Controller
    {
        readonly private ApplicationDbContext _db;

        public EditarController(ApplicationDbContext db)
        {
            _db = db;
        }


        [HttpGet]
        public IActionResult Index(int?Id)
        {
            if (Id == null || Id == 0) 
            {
                return NotFound();
            }
           
            DayuseModel dayuse = _db.Dayuse.FirstOrDefault(x => x.Id ==Id) ;

            if (dayuse == null) 
            {
                return NotFound();
            }

            return View(dayuse);
        }

        [HttpPost]
        public IActionResult Index(DayuseModel dayuse)
        {
            if (ModelState.IsValid)
            {
                _db.Dayuse.Update(dayuse);
                _db.SaveChanges();

                return RedirectToAction("Index", "Listagem");
            }
            return View(dayuse);

        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var dayuse = _db.Dayuse.FirstOrDefault(x => x.Id == id);

            if (dayuse == null)
            {
                return NotFound();
            }

            _db.Dayuse.Remove(dayuse);
            _db.SaveChanges();

            return RedirectToAction("Index", "Listagem");
        }
    }
}

Controllers/HomeController.cs
using Controle.data;
using Controle.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Controle.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
    
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
      
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ListagemController.cs
using Controle.data;
using Controle.Models;
using Microsoft.AspNetCore.Mvc;

namespace Controle.Controllers
{
    public class ListagemController : Controller
    {
        readonly private ApplicationDbContext _db;
        public ListagemController(ApplicationDbContext db)
        {
            _db = db;
            
        }
        public IActionResult Index()
        {
            IEnumerable<DayuseModel>dayuse = _db.Dayuse;
            return View(dayuse);
        }
    }
}

Views/Cadastro/Index.cshtml
@model DayuseModel

@{
    ViewData["Title"] = "Cadastro de Day Use";
}

<form method="post" asp-controller="Cadastro" asp-action="Index">

    <div class="text-center">
        <h1 class="display-4 mb-5 my-4">Cadastro de Venda</h1>

        @if (TempData["Mensagem de Sucesso"] != null)
        {
            <div class="alert alert-dismissible alert-success" role="alert">
                @TempData["Mensagem de Sucesso"]
            </div>
        }

        @if (TempData["Mensagem de Erro"] != null)
        {
            <div class="alert alert-dismissible alert-danger" role="alert">
                @TempData["Mensagem de Erro"]
            </div>
        }

        <div class="row mb-3">
            <div class="col-md-6 mb-3">
                <input class="form-control" type="text" asp-for="Nome" placeholder="Nome Completo">
                <span class="text-danger" asp-validation-for="Nome"></span>
            </div>
            <div class="col-md-6 mb-3">
                <input class="form-control" type="tel" asp-for="Telefone" pattern="[(][0-9]{2}[)][0-9]{5}-[0-9]{4}" placeholder="(11)99999-9999">
                <span class="text-danger" asp-validation-for="Telefone"></span>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6 mb-3">
                <input class="form-control" type="text" asp-for="Pulseira" placeholder="Numero da Pulseira">
                <span class="text-danger" asp-validation-for="Pulseira"></span>
            </div>
            <div class="col-md-6 mb-3">
                <input class="form-control" asp-for="DataVenda" type="date" placeholder="Data">
                <span class="text-danger" asp-validation-for="DataVenda"></span>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-4 mb-3">
                <select class="form-control" asp-for="Aluno" id="Aluno">
                    <option value=true>Aluno</option>
                    <option value=false>Não Aluno</option>
                </select>
                <span class="text-danger" asp-validation-for="Aluno"></span>
            </div>
            <div class="col-md-4 mb-3">
                <div class="input-group gap-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text">R$</span>
                    </div>
                    <input type="text" class="form-control" asp-for="Preco" placeholder="Preço">
                </div>
                <span class="text-danger" asp-validation-for="Preco"></span>
            </div>
            <div class="col-md-4 mb-3">
                <select class="form-control" asp-for="FormaPagamento" id="FormaPagamento">
                    <option value=Debito>Debito</option>
                    <option value=Credito>Credito</option>
                    <option value="Pix">Pix</option>
                    <option value="TP">TP</option>
                    <option value="GP">GP</option>
                </select>
                <span class="text-danger" asp-validation-for="FormaPagamento"></span>
            </div>
        </div>

        <div class="d-flex justify-content-center align-items-center mt-4 gap-2">
            <a type="button" class="btn btn-primary" asp-controller="Home" asp-action="Index">Voltar</a>
            <button type="submit" class="btn btn-success">Cadastrar</button>
        </div>
    </div>
</form>

Views/Editar/Index.cshtml
@model DayuseModel

@{
    ViewData["Title"] = "Editar de Day Use";
}

<form method="post" asp-controller="Editar" asp-action="Index">
    <div class="text-center">
        <h1 class="display-4 mb-5">Cadastro de Venda</h1>

      

        <div class="row mb-3 gap-2 mt-5">
            <input class="form-control col" type="text" asp-for="Nome" placeholder="Nome Completo">
            <input class="form-control col" type="tel" asp-for="Telefone" pattern="[(][0-9]{2}[)][0-9]{5}-[0-9]{4}" placeholder="(11)99999-9999">
        </div>
        <div class="row mb-3 gap-2">
            <span class="text-danger col" asp-validation-for="Nome"></span>
            <span class="text-danger col" asp-validation-for="Telefone"></span>
        </div>
        <div class="row mb-3 gap-2">
            <input class="form-control col" type="text" asp-for="Pulseira" placeholder="Numero da Pulseira">
            <input class="form-control col" asp-for="DataVenda" type="date" placeholder="Data">
        </div>
        <div class="row mb-3 gap-2">
            <span class="text-danger col" asp-validation-for="Pulseira"></span>
            <span class="text-danger col" asp-validation-for="DataVenda"></span>
        </div>
        <div class="row mb-3 gap-2">
            <select class="form-control col" asp-for="Aluno" id="Aluno">
                <option value=true>Aluno</option>
                <option value=false>Não Aluno</option>
            </select>
            <input type="text" class="form-control col" asp-for="Preco" placeholder="Preço">
            <select class="form-control col" asp-for="FormaPagamento" id="FormaPagamento">
                <option value=Debito>Debito</option>
                <option value=Credito>Credito</option>
                <option value="Pix">Pix</option>
                <option value="TP">TP</option>
                <option value="GP">GP</option>
            </select>

            <div class="row mb-3 gap-2">
                <span class="text-danger col" asp-validation-for="Aluno"></span>
                <span class="text-danger col" asp-validation-for="Preco"></span>
                <span class="text-danger col" asp-validation-for="FormaPagamento"></span>
            </div>

        </div>

        <div class="d-inline-flex justify-content-center align-items-md-center mt-2 gap-2">

            <a type="button" class="btn btn-primary " asp-controller="Listagem" asp-action="Index"><i class="bi bi-arrow-return-left mx-2"></i>Voltar</a>

            <button type="submit" class="btn btn-success "><i class="bi bi-check-square mx-2"></i>Editar</button>
        </div>
    </div>
</form>

Views/Home/Index.cshtml
<div class="container d-flex flex-column align-items-center">
    <div class="text-center">
        <h1 class="display-4 mt-4">SEJA BEM VINDO !</h1>
    </div>
    <div class="d-flex justify-content-center mt-4 h-50 w-50">
        <img src="https://w12evostorage.w12app.com.br/evo/upload-imagem/27333/5ed9ad72-b32e-4cf8-861d-9f54452a8e6c.png" alt="Logo" class="img-fluid " />
    </div>
</div>

Views/Listagem/Index.cshtml
@model IEnumerable<DayuseModel>

@{
    ViewData["Title"] = "Lista de Day Use";
}
<div class="text-center">
    <h1 class="display-4  my-4" style="margin-bottom:70px">Lista de Day Use</h1>
        @if (TempData["Mensagem de Sucesso"] != null)
        {
            <div class="alert alert-dismissible alert-success" role="alert">
                @TempData["Mensagem de Sucesso"]
            </div>
         }

        @if (TempData["Mensagem de Erro"] != null)
        {
            <div class="alert alert-dismissible alert-danger" role="alert">
                @TempData["Mensagem de Erro"]
            </div>
         }
    
    <table class="table" id="lista">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Telefone</th>
                <th scope="col">Aluno</th>
                <th scope="col">Pulseira</th>
                <th scope="col">Data de Venda</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null)
            {
                @foreach(var dayuse in Model)
                {
                    <tr>
                        <td>@dayuse.Nome</td>
                        <td>@dayuse.Telefone</td>
                        @if(dayuse.Aluno == true)
                        {
                            <td>Aluno</td>
                        }
                        else
                        {
                            <td>Não Aluno</td>
                        }
                        <td>@dayuse.Pulseira</td>
                        <td>@dayuse.DataVendaFormatada</td>
                        <td>
                            <a asp-controller="Editar" asp-action="Index" asp-route-id="@dayuse.Id" class="btn btn-outline-success "> <i class="bi bi-pencil-square mx-2"></i> Editar</a>
                            <button type="button" class="btn btn-outline-danger" onclick="openDeleteModal(@dayuse.Id)"><i class="bi bi-trash mx-2"></i>Excluir</button>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>


<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirmar Exclusão</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                Tem certeza de que deseja excluir este item?
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <form id="deleteForm" method="post"asp-controller="Editar" asp-action="Delete">
                    <input type="hidden" id="deleteId" name="id" value="" />
                    <button type="submit" class="btn btn-danger">Excluir</button>
                </form>
            </div>

        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]Controle JR10</title>
    <link rel="stylesheet" href="https://cdn.lineicons.com/4.0/lineicons.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous" />
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/v/dt/dt-2.1.3/datatables.min.css"/>
</head>

<body>
    <div class="wrapper">
        <aside id="sidebar">
            <div class="d-flex">
                <button class="toggle-btn" type="button">
                    <i class="lni lni-grid-alt"></i>
                </button>
                <div class="sidebar-logo">
                    <a asp-controller="Home" class="text-decoration-none" asp-action="Index">Arena JR10</a>
                </div>
            </div>
            <ul class="sidebar-nav">
                <li class="sidebar-item">
                    <a class="sidebar-link text-decoration-none">
                        <i class="lni lni-user"></i>
                        <span>Perfil</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a asp-controller="Cadastro" asp-action="Index" class="sidebar-link text-decoration-none">
                        <i class="bi bi-file-plus"></i>
                        <span>Venda de Day Use</span>
                    </a>
                </li>
                <li class="sidebar-link collapsed">
                    <a asp-controller="Listagem" asp-action="Index" class="sidebar-link text-decoration-none">
                        <i class="lni lni-agenda"></i>
                        <span>Lista de Day Use</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link text-decoration-none">
                        <i class="lni lni-popup"></i>
                        <span>Notification</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link text-decoration-none">
                        <i class="lni lni-cog"></i>
                        <span>Setting</span>
                    </a>
                </li>
            </ul>
            <div class="sidebar-footer">
                <a href="#" class="sidebar-link text-decoration-none">
                    <i class="lni lni-exit"></i>
                    <span>Logout</span>
                </a>
            </div>
        </aside>
        <div class="main p-3">
            <div class="text-center">
                <div class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/2.1.3/js/dataTables.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/script.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>